# Generated by Django 5.1.1 on 2024-10-04 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='max_capacity',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
